services:
  fastapi-app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql-c
      - MYSQL_PORT=3306
      - MYSQL_USER=melissa
      - MYSQL_PASSWORD=admin@melissa
      - MYSQL_DB=melissa-db
      - POSTGRES_HOST=postgres-c
      - POSTGRES_PORT=5432
      - POSTGRES_USER=melissa
      - POSTGRES_PASSWORD=admin@melissa
      - POSTGRES_DB=melissa-db
      - ORACLE_HOST=oracle-c
      - ORACLE_PORT=1521
      - ORACLE_USER=melissa
      - ORACLE_PASSWORD=admin@melissa
      - ORACLE_SERVICE=melissadb
      - MSSQL_HOST=mssql-c
      - MSSQL_PORT=1433
      - MSSQL_USER=melissa
      - MSSQL_PASSWORD=admin@melissa
      - MSSQL_DB=melissa-db
      - MONGO_HOST=mongodb-c
      - MONGO_PORT=27017
      - MONGO_USER=melissa
      - MONGO_PASSWORD=admin@melissa
      - MONGO_DB=melissa-db
      - SECRET_KEY=9a7c36a4f91048b3b4d45d8b725c8397a6e191d918c5e3faef625a62bc2b88dc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    networks:
      - dbnet
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 3
    depends_on:
      db-init:
        condition: service_completed_successfully

  db-init:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    container_name: db-init
    volumes:
      - ./sql:/app/sql
    environment:
      - MYSQL_HOST=mysql-c
      - MYSQL_PORT=3306
      - MYSQL_ADMIN_USER=root
      - MYSQL_ADMIN_PASSWORD=admin@melissa
      - MYSQL_DB=melissa-db
      - POSTGRES_HOST=postgres-c
      - POSTGRES_PORT=5432
      - POSTGRES_ADMIN_USER=melissa
      - POSTGRES_ADMIN_PASSWORD=admin@melissa
      - POSTGRES_DB=melissa-db
      - ORACLE_HOST=oracle-c
      - ORACLE_PORT=1521
      - ORACLE_ADMIN_USER=melissa
      - ORACLE_ADMIN_PASSWORD=admin@melissa
      - ORACLE_SERVICE=melissadb
      - MSSQL_HOST=mssql-c
      - MSSQL_PORT=1433
      - MSSQL_ADMIN_USER=sa
      - MSSQL_ADMIN_PASSWORD=Admin@melissa123
      - MSSQL_DB=melissa-db
      - MONGO_HOST=mongodb-c
      - MONGO_PORT=27017
      - MONGO_ADMIN_USER=melissa
      - MONGO_ADMIN_PASSWORD=admin@melissa
      - MONGO_DB=melissa-db
      - MONGO_AUTH_DB=admin
    entrypoint: ["python", "database/db_init.py"]
    networks:
      - dbnet

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=9a7c36a4f91048b3b4d45d8b725c8397a6e191d918c5e3faef625a62bc2b88dc
      - MAPBOX_API_KEY=""
    volumes:
      - superset_home:/app/superset_home
    networks:
      - dbnet
    restart: always

networks:
  dbnet:
    external: true
    name: mimie_dbnet

volumes:
  superset_home:


# 